name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Subir Ambiente e Executar Testes
        run: |
          docker-compose up --build --exit-code-from tests

      - name: Derrubar containers
        if: always()
        run: |
          docker-compose down